### ISSUE TITLE
Doesn't work on Chrome properly

### ISSUE THREAD

**Issue by mkpazon** [Furqankhanzada/flutter_eCommerce_ui_kit#3]
First off, I really like your project. Feels really native on mobile.

Although this project was meant for mobile, it would be nice if it can work on web as well.

I followed the steps in https://flutter.dev/docs/get-started/web

Got it to run in Chrome, but the images in the card views are not rendering. Interestingly enough some of the screens were able to render the images.

**Comment by Furqankhanzada** [comment]
@mkpazon now its fully supports web version. i updated it to flutter 2.2.
