### ISSUE TITLE
Version Miss-Matched

### ISSUE THREAD

**Issue by amritesh-21** [Furqankhanzada/flutter_eCommerce_ui_kit#7]
How to run this on the latest flutter version, many of the keywords are showing to change , but still showing error

**Comment by Furqankhanzada** [comment]
what are the errors ?

**Comment by amritesh-21** [comment]
**Not Errors , these warnings are showing **

Sir Please fix this :(


![Screenshot (16)](https://user-images.githubusercontent.com/74090794/124594189-251f0400-de7d-11eb-8a42-d14ee0de77f5.png)
![Screenshot (17)](https://user-images.githubusercontent.com/74090794/124594199-27815e00-de7d-11eb-85a3-64fcdc7c4597.png)
![Screenshot (18)](https://user-images.githubusercontent.com/74090794/124594205-28b28b00-de7d-11eb-81ed-e948b626220b.png)
![Screenshot (15)](https://user-images.githubusercontent.com/74090794/124594209-29e3b800-de7d-11eb-9e8a-37bda227fbae.png)

**Comment by amritesh-21** [comment]
**This error is coming while debugging**


![Screenshot (19)](https://user-images.githubusercontent.com/74090794/124596001-5a2c5600-de7f-11eb-9781-cd3f32d171cc.png)

**Comment by Furqankhanzada** [comment]
@amritesh-21 fixed.
